### ISSUE TITLE
HighlightMissing getting called

### ISSUE THREAD

**Issue by mattboehm** [alfredodeza/coveragepy.vim#10]
When I try to run any of the commands, I see a ton of echos about "Current buffer" and file. While a report eventually loads, the signs don't seem to function properly

Current buffer shows as an absolute path without .py on the end
file shows as a relative path with .py on the end

I traced this down to this function in the code: https://github.com/alfredodeza/coveragepy.vim/blob/master/ftplugin/python/coveragepy.vim#L106

If I change that `[1]` to a `[0]` (essentially negating the stripping of the `.py` I believe,) I see no echos and everything appears to work.

**Comment by mattboehm** [comment]
correction: I still see the echos, but sign highlighting now works.

**Comment by alfredodeza** [comment]
@mattboehm thanks for the issue report. The stripping of `.py` shouldn't matter, all this is doing is trying to grab the path to attempt a match to the current buffer.

However, the echos are indeed something that was probably left from debugging. I will remove them.

That should take care of the astray echos, but I don't really understand the issues you are having with the signs.

Could you describe more how it doesn't function properly? What is it that you expect that is not happening ?

**Comment by alfredodeza** [comment]
Pushed commit 4cc4e1bfa9ec434a27769c3a4768626e0b4a46ec that should take care of the `echo` issue

**Comment by mattboehm** [comment]
@alfredodeza Thanks for the quick response and the great plugin =).

When the echos showed, they took up more than a page so I had to scroll down to see them all. I believe if I dismissed them with "q", the signs did not show properly whereas if I dismissed them by scrolling to the bottom, things worked properly.

I'll pull the latest code later today and see if that fixes my problems.

**Comment by alfredodeza** [comment]
Awesome, thank you for testing it out!

**Comment by mattboehm** [comment]
Thanks, everything looks good now.

**Comment by alfredodeza** [comment]
Thank you very much for taking the time to open the issue and bring it up. I had no idea I left those statements around :)
