### ISSUE TITLE
Add support for "branch coverage" (was: Calling "Coveragepy report" yields "Error detected while processing function …")

### ISSUE THREAD

**Issue by okurz** [alfredodeza/coveragepy.vim#12]
Calling ":Coveragepy report" from vim yields

```
Error detected while processing function <SNR>78_Proxy..<SNR>78_CoveragepyReport..<SNR>78_ReportParse..<SNR>78_LineNumberParse:
line   10:
E727: Start past end
E714: List required
```

There is a `.coverage` in the current directory.

**Comment by alfredodeza** [comment]
Ouch. Let me try and reproduce. Thanks for reporting!

**Comment by alfredodeza** [comment]
If you could, would you mind inserting this between line 219 and 220 in the `s:LineNumberParse` function?:

    echom a:numbers

That function is breaking because that value has something that it can't handle

**Comment by okurz** [comment]
I added the debug output you asked me for.

 * First, I just called "Coveragepy report" after I changed my code to have 100% coverage -->  "Coveragepy report" *SUCCESS*
 * Deleting .coverage --> message that coverage data is missing *SUCCESS*
 * Executing only some tests yielding lower coverage --> *FAIL*, output:
```
   201, 266-268, 273, 280, 283, 328-332, 337-342, 345, 367, 407-458, 467-477, 506, 514, 520-521, 524, 265->266, 279->280, 282->283, 291->-297, 291->-295,
291->-294, 291->-293, 291->-291, 327->328, 334->337, 344->345, 382->385, 387->390, 391->394, 462->467, 517->520, 523->524
Error detected while processing function <SNR>79_Proxy..<SNR>79_CoveragepyReport..<SNR>79_ReportParse..<SNR>79_LineNumberParse:
line   11:
E727: Start past end
E714: List required
```
I assume lineNumberParse can not handle the branch coverage report tokens so I disabled and reran
 * Set "branch = False" in my .coveragerc and rerun same test --> *FAIL*, different output:
```
   201, 266-268, 273, 280, 283, 328-332, 337-342, 345, 367, 407-458, 467-477, 506, 514, 520-521, 524
Error detected while processing function <SNR>79_Proxy..<SNR>79_HighlightMissing:
line    8:
E684: list index out of range: 1
E15: Invalid expression: matchlist(expand("%:p"), '\v(.*)(.py)')[1]
```

**Comment by alfredodeza** [comment]
Very good catch, thanks for looking into this. It should be straightforward to fix

**Comment by okurz** [comment]
BTW, if you want to also visualize branch coverage: the html generator from python coverage module uses yellow for uncovered branches, e.g. you could use something like
```
hi branchuncovered guifg=#ffff00 guibg=yellow ctermfg=40 ctermbg=40
```
in your code maybe?

**Comment by alfredodeza** [comment]
That looks fantastic. I agree!

**Comment by okurz** [comment]
@alfredodeza did I get you right that *you* will prepare a fix some time? I am not feeling confident I can really provide a good PR at this time though I would be happy to help testing a change.

**Comment by alfredodeza** [comment]
yep,  I will tackle this one. I just fixed a couple of other issues today, this one is coming up next :)

**Comment by alfredodeza** [comment]
With commit b3677624cf535fc7deb25efe71d695891daccdd8 this should no longer break, but alas, proper reporting on branch coverage is not yet done.

At least it doesn't break! I will try to get proper branch coverage reporting soon

**Comment by okurz** [comment]
hm, did not fully work for me. If without '--branch' everything seems to be ok now but when gathering coverage with '--branch':
```
Error detected while processing function <SNR>77_Proxy..<SNR>77_HighlightMissing:
line   14:
E474: Invalid argument
```

**Comment by alfredodeza** [comment]
This is odd, because I can't replicate. This is what I am trying:

    coverage run --branch `which py.test`
    vim file.py
    :Coveragepy show

I can navigate and see covered/uncovered lines. Granted, I am not parsing branch coverage yet. But I can't get this to break. If you could, would you mind giving me something so I can replicate?

**Comment by alfredodeza** [comment]
I was finally able to get something that would replicate the problem. Will fix soon

![screen shot 2016-01-19 at 4 08 12 pm](https://cloud.githubusercontent.com/assets/317847/12432046/e4ec8172-bec6-11e5-9a77-1e20e449afad.png)

**Comment by okurz** [comment]
well, trying to come up with a "minimum failing example" I struggle because everything looks ok so can you disregard my last but it's good you can know replicate the "HighlightMissing" something :-)

**Comment by alfredodeza** [comment]
@okurz can you try and use the newest changes from master? I have something that should work for you

**Comment by alfredodeza** [comment]
Commit a44f1bc715654fd9e13796cd7d1a04304c256a9e

**Comment by okurz** [comment]
It works perfectly. Thank you very much.
