### ISSUE TITLE
Broken with coverage 4.0.3

### ISSUE THREAD

**Issue by bowensong** [alfredodeza/coveragepy.vim#13]
After I updated coverage to 4.0.3, all files are100% covered in the plugin, even the fact is they are not 100% covered.

**Comment by alfredodeza** [comment]
So I found the issue. The newer versions of coverage include `.py` when reporting the paths. Previous versions didn't, so when looking at the paths, the plugin was matching incorrectly.

Bummer. Hopefully I will get a fix soon-ish. Thanks for reporting!

**Comment by alfredodeza** [comment]
@bowensong would you mind pulling the latest version and try it out? This commit fixes it d996f0ebf7c7d8b194f70fa8b4bb32e6929fd873

**Comment by bowensong** [comment]
@alfredodeza the `Coveragepy show` command works now, but in the `Coveragepy report` window, navigate between files still not working, error message is: `Could not load file: __init__.py.py`

**Comment by alfredodeza** [comment]
@bowensong oh great catch. I can't win huh?

The latest commit fixes that problem, hopefully that gets you everything working

3298ed3b746fe18b691828311d793a634a2622f6

Let me know!

**Comment by bowensong** [comment]
Cool, thanks! Now it works.
