### ISSUE TITLE
Error when using this plugin

### ISSUE THREAD

**Issue by esc** [alfredodeza/coveragepy.vim#14]
Hi,

I get the following error when using this plugin

```
Error detected while processing function <SNR>128_Proxy..<SNR>128_CoveragepyReport..<SNR>128_ReportParse..<SNR>128_LineNumberParse:
line   10:
E727: Start past end
E714: List required
Error detected while processing function <SNR>128_Proxy..<SNR>128_CoveragepyReport..<SNR>128_ReportParse:
line    9:
E706: Variable type mismatch for: all_line_nos
```

**Comment by alfredodeza** [comment]
@esc are you using branch coverage? Also, what version of coverage.py are you using? 

Can you try doing `:Coveragepy session` to see how that looks like?

**Comment by esc** [comment]
So I found out why this happens, my coverage output has the following in it:

```
12, 16, 11->12
```

And I presume that the splitter can not handle the `->` sign.

**Comment by alfredodeza** [comment]
@esc we do have support for that:
https://github.com/alfredodeza/coveragepy.vim/blob/master/ftplugin/python/coveragepy.vim#L232-L237

Would you be so kind and provide the following so I can debug this:

* coverage version
* `:Coveragepy session` output

**Comment by esc** [comment]
Version:

```
coverage --version
Coverage.py, version 4.0.3.
Documentation at https://coverage.readthedocs.org
```

Session output:

```

Error detected while processing function <SNR>128_Proxy..<SNR>128_LastSession..<SNR>128_CoveragepyReport..<SNR>128_ReportParse..<SNR>128_LineNumberParse:
line   11:
E727: Start past end
E714: List required
Error detected while processing function <SNR>128_Proxy..<SNR>128_LastSession..<SNR>128_CoveragepyReport..<SNR>128_ReportParse:
line    9:
E706: Variable type mismatch for: all_line_nos
```

**Comment by esc** [comment]
Ah, I think I had an old version of the plugin w/o the support for `->`, sorry for the noise.

**Comment by alfredodeza** [comment]
@esc great! thanks so much for taking the time to report anyway :)
