### ISSUE TITLE
Request: alternative, subtler display style.

### ISSUE THREAD

**Issue by amcgregor** [alfredodeza/coveragepy.vim#16]
It would be nice, for integration with other gutter symbols and a less-strong desire to only use the current presentation for brief glances (ze goggles, zey do nothing!), if lines _not_ covered by tests be annotated with a warning-level "TT" compared to the current, high-contrast background.

Thanks!

**Comment by alfredodeza** [comment]
I am not sure I understand fully. For covered lines a green block is used, for uncovered it is red. You would only want to change uncovered lines with the characters "TT" ? what do you mean by "warning-level"? a color?

I could allow some configuration probably but that could be tricky. Here is the part where the code highlights certain sections:

    hi SignColumn guifg=#004400 guibg=green ctermfg=40 ctermbg=40
    hi uncovered guifg=#ff2222 guibg=red ctermfg=1 ctermbg=1
    hi covered guifg=#004400 guibg=green ctermfg=40 ctermbg=40
    hi branchuncovered guifg=#ffff00 guibg=yellow ctermfg=yellow ctermbg=yellow
    sign define uncovered text=XX texthl=uncovered
    sign define covered text=XX texthl=covered
    sign define branchuncovered text=XX texthl=branchuncovered

**Comment by blueyed** [comment]
I think an option to only highlight uncovered (or covered) lines makes sense.
If you work on a project with high coverage, it is better on the eyes (and the sign column) to only highlight/mark parts where there is no coverage.

**Comment by merwok** [comment]
I agree with this request!  I’m only using a few vim plugins at the moment, and I like for example how the gitgutter plugin shows green `+` and  red `-` for added/removed lines in a way that’s helpful and discreet.  Two-column wide solide bars of flashy green and red is a bit in your face :)

**Comment by merwok** [comment]
This is git-gutter:

![screen](https://user-images.githubusercontent.com/635179/32584874-9f92c0b4-c4c8-11e7-9596-1df6c7718879.png)

At the moment, coveragepy overwrites the gutter with the big flashy bar.  It would be great if we could easily control how coveragepy shows lines missing (no need to annotate lines covered in my opinion).

Another plugin uses highlight groups and leaves the gutter alone: https://github.com/mgedmin/coverage-highlight.vim#coverage-highlightvim

**Comment by alfredodeza** [comment]
@merwok when you say 'the gutter' you mean the sign column or the gitgutter plugin (or both?) 

I can try and make it somewhat configurable, will have an update soon

**Comment by blueyed** [comment]
@alfredodeza 
Just for information: there is also https://github.com/google/vim-coverage, which tries to be a provider for different coverage sources, and it had some activity lately.
I still have some local changes for it, and it might make sense to join forces over there.
They have a provider for coveragepy by now.

**Comment by merwok** [comment]
I meant the sign column.  After installing git-gutter I thought that «gutter» was a general term for this column :)

**Comment by merwok** [comment]
FWIW I tried to use five different coverage plugins yesterday, including google’s which seems the heaviest to install and at runtime, and none of them was working in a satisfying way.  The two closest are this plugin and mgedmin/coverage-highlight.vim, each with only one or two small issues.

**Comment by blueyed** [comment]
@merwok 
I feel your pain, went through it myself a while ago.
But that's why I think joining forces makes sense, and Google's is meant to be a generic framework.
For google/coverage-vim I've fixed for example that only its own signs get cleared, which is an issue with all of the plugins I've tried.
Anyway, I just wanted to mention this.

**Comment by alfredodeza** [comment]
@blueyed that issue is fixed with e479a93

**Comment by alfredodeza** [comment]
Potential fix/improvement for this issue is at 3187805c374d3d2d2111f65e058d0108d6b41d54

There is also support for custom sign char (shown here with defaults):

    let g:coveragepy_uncovered_sign = '^'

Can you guys please try this out and see if it helps out or not? Thanks

**Comment by blueyed** [comment]
@alfredodeza 
Not really: https://github.com/alfredodeza/coveragepy.vim/commit/e479a93c0e6496549995f8fc20642c7097051b21#commitcomment-25516917

**Comment by alfredodeza** [comment]
Fixed in master, there is a 'subtler display' now, with no green/red bars.

**Comment by merwok** [comment]
Thanks!
