### ISSUE TITLE
Should only unplace own signs

### ISSUE THREAD

**Issue by blueyed** [alfredodeza/coveragepy.vim#18]
Nice plugin!

I've noticed however that it would unplace all signs with `:Coveragepy unshow` (https://github.com/alfredodeza/coveragepy.vim/blob/599f695fa0e4f6077e3e91d5a5cccb028fecf2e2/ftplugin/python/coveragepy.vim#L85-L87), but signs from other plugins, e.g. https://github.com/tomtom/quickfixsigns_vim/ should be kept).

**Comment by alfredodeza** [comment]
Addressed with d88d70bc0dcce0cf4974b36ebf58a340290a7e4e

Mind taking a look? Or just reviewing if you are no longer using this plugin so I can merge to master

**Comment by alfredodeza** [comment]
This has been fixed in master
