### ISSUE TITLE
Signs are always placed in the first pane

### ISSUE THREAD

**Issue by merwok** [alfredodeza/coveragepy.vim#22]
Hello!  I’m trying out this plugin.  I work with tabs and panes a lot and happened to have the plugin file, a Python module and its tests all open in three panes.  When running Coveragepy report in the module or tests file pane, the first one got the gutter decoration.

**Comment by alfredodeza** [comment]
mind grabbing a screenshot so I can have a better idea of what you are experiencing? Thanks!

**Comment by merwok** [comment]
![vimgutter](https://cloud.githubusercontent.com/assets/635179/23619539/f5ae0668-0261-11e7-982c-c9a4b5a678c0.png)

**Comment by merwok** [comment]
With these two files:

![screenshot](https://user-images.githubusercontent.com/635179/32584625-5afdf172-c4c7-11e7-9f7c-8b2a36ad21c6.png)

No matter where I run `:Coveragepy report`, it’s always the first split that gets the annotations (the big green/red margin), never the one on the right side.

With `:Coveragepy show`, it seems like there is a global toggle rather than a per-file option.  If the left file is annotated and I move to the right one, the first `show` will turn off the annotations on the left file, and a second `show` will finally annotate the right-side file.

I’ve tried five coverage-vim plugins today and none of them is simple to install, simple to use and nice to see.  This one is the closest!  The desirable behaviour for me is: one command to annotate all files (i.e. report), one command to turn on/off in one file (show).

(Also a style that doesn’t overwrite my git gutter and is more pleasant → #16, and a pony :)

**Comment by alfredodeza** [comment]
@merwok good catch, thank you for providing the screenshot. You are right that the plugin is failing to use a per-file setting. Will try to address this soon.

**Comment by alfredodeza** [comment]
@merwok thank you so much for taking the time to report this, and for being patient :)

This particular issue is fixed with https://github.com/alfredodeza/coveragepy.vim/commit/e479a93c0e6496549995f8fc20642c7097051b21 

Could you try that commit out and see how that works for you? I tested it out and respected the sign placement per buffer. Once you verify I'll push that to master. 

Thanks!

**Comment by merwok** [comment]
Issues with that version:

- When I run `:Coveragepy show` in one buffer (in a split), other buffers get a huge green bar (it seems to be the «neutral» sign, so this could be resolved by #16 if we get a way to show nothing for covered lines).  In the screenshot, I ran my coverage command then coveragepy on the right-hand sign split, and the screenshot is from another split, you can see the new code with the `+` signs from git-gutter and the existing code gets the flashy green.  If I run coveragepy show in that file, the new code gets the red signs.
![screen1](https://user-images.githubusercontent.com/635179/32622817-2cf7a4f4-c552-11e7-935f-eccce8cc7a0f.png)

- The report and show commands take a very long time because they try to annotate all modules in my active virtualenv, ignoring the config I have in my tox.ini file.

- Coverage signs are incorrect.

**Comment by alfredodeza** [comment]
Let's take it step by step though, not sure that your items are strictly related to *this* issue.

For *this* issue: in a split screen with more than one buffer: Do you get control of `show` *per* buffer? That is: is the reported (incorrect) behavior of always using the first pane solved by commit e479a93 ?

I am working on fixing the green block, but lets try to get this issue addressed first.

**Comment by alfredodeza** [comment]
Sign column blocks are now removed with 3187805c374d3d2d2111f65e058d0108d6b41d54 you can try that on top of e479a93

**Comment by alfredodeza** [comment]
These changes have been merged to master. This issue (signs always placed in first pane) is resolved there, with commit a6c2f6feb6b1adeabed19f46a5a641c936f4026d

**Comment by merwok** [comment]
Thanks a lot!  I’ll be able to test soon.
