### ISSUE TITLE
Can we have an option to not open LastSession.coveragepy window at the bottom?

### ISSUE THREAD

**Issue by shadyabhi** [alfredodeza/coveragepy.vim#24]
Sometimes, all I want to see is lines that are not covered and not interested in the whole report.

**Comment by alfredodeza** [comment]
You mean like `:Coveragepy refresh` ? 

https://github.com/alfredodeza/coveragepy.vim#refresh

Or something different?

**Comment by shadyabhi** [comment]
Damn, I'm so sorry about this. That's what I needed.

**Comment by alfredodeza** [comment]
No worries, happy to help
