### ISSUE TITLE
Detecting coverage executable, handling py2/py3

### ISSUE THREAD

**Issue by FedericoCeratto** [alfredodeza/coveragepy.vim#28]
When both /usr/bin/python-coverage and /usr/bin/python3-coverage are installed, coveragepy.vim uses the first one even if the coverage report has been created from Python 3.
When only /usr/bin/python3-coverage is installed, coveragepy.vim does not use it.

Using the wrong version leads to misleading ouput showing some files as 100% covered.

Some hints, warnings or autodetection would be nice. Thanks!

**Comment by alfredodeza** [comment]
Can you try the tip of master? I think that should address your problem. Also, I've added a configuration flag (documented as well in the README) to allow forcing it if the detection doesn't work well enough for you

**Comment by alfredodeza** [comment]
I believe this is working fine now. Feel free to re-open if you have any issues. Thanks for reporting it!
